const careerDB = {
    eduLevels: [
        { hu: "Általános iskola", en: "Primary School", de: "Grundschule" },
        { hu: "Gimnáziumi érettségi", en: "High School Diploma", de: "Abitur" },
        { hu: "Szakközépiskolai érettségi", en: "Vocational High School", de: "Berufliche Oberschule" },
        { hu: "Szakmunkás bizonyítvány", en: "Vocational Certificate", de: "Berufsabschluss" },
        { hu: "Technikusi vizsga", en: "Technical Diploma", de: "Technikerabschluss" },
        { hu: "Főiskolai diploma (BSc)", en: "Bachelor's Degree", de: "Bachelor-Abschluss" },
        { hu: "Egyetemi diploma (MSc)", en: "Master's Degree", de: "Master-Abschluss" },
        { hu: "Szakács szakképesítés", en: "Chef Qualification", de: "Koch Qualifikation" },
        { hu: "OKJ Tanúsítvány", en: "Professional Cert.", de: "Berufszertifikat" },
        { hu: "Doktori fokozat (PhD)", en: "Doctoral Degree", de: "Doktortitel" },
        { hu: "Mestervizsga", en: "Master Craftsman", de: "Meisterbrief" },
        { hu: "Vendéglátóipari végzettség", en: "Hospitality Cert.", de: "Gastronomieabschluss" },
        { hu: "Informatikai szakirány", en: "IT Specialization", de: "IT-Spezialisierung" },
        { hu: "Logisztikai szakirány", en: "Logistics Cert.", de: "Logistik-Fachabschluss" },
        { hu: "Pénzügyi szakirány", en: "Finance Cert.", de: "Finanz-Fachabschluss" },
        { hu: "Mezőgazdasági szakmunkás", en: "Agricultural Worker", de: "Landwirtschaftsdiplom" },
        { hu: "Egészségügyi végzettség", en: "Nursing Cert.", de: "Pflegeabschluss" },
        { hu: "Gépészeti szakirány", en: "Mechanical Cert.", de: "Maschinenbauabschluss" },
        { hu: "Villamosipari technikus", en: "Electrical Technician", de: "Elektrotechniker" },
        { hu: "Építőipari szakmunkás", en: "Construction Worker", de: "Bauarbeiter-Abschluss" },
        { hu: "Autószerelő mester", en: "Master Mechanic", de: "Kfz-Meister" },
        { hu: "Nyelvi diploma", en: "Language Diploma", de: "Sprachdiplom" },
        { hu: "Vámügyintéző", en: "Customs Officer Cert.", de: "Zollfachkraft" },
        { hu: "Szállítmányozási menedzser", en: "Freight Manager", de: "Speditionskaufmann" },
        { hu: "Targonca jogosítvány", en: "Forklift License", de: "Staplerschein" },
        { hu: "Darukezelői vizsga", en: "Crane Operator Cert.", de: "Kranführerschein" },
        { hu: "Nehézgépkezelői vizsga", en: "Heavy Machine License", de: "Baumaschinenführer" },
        { hu: "Biztonsági őr vizsga", en: "Security License", de: "Sicherheitsprüfung" },
        { hu: "Hegesztő minősítés", en: "Welding Cert.", de: "Schweißzertifikat" },
        { hu: "CNC gépkezelő", en: "CNC Operator Cert.", de: "CNC-Zertifikat" }
    ],
    jobs: [
        { hu: "Raktáros", en: "Warehouse Worker", de: "Lagerarbeiter" },
        { hu: "Teherautó sofőr (C,E)", en: "Truck Driver (C,E)", de: "LKW-Fahrer" },
        { hu: "Eladó / Pénztáros", en: "Sales Assistant", de: "Verkäufer" },
        { hu: "Szakács", en: "Chef", de: "Koch" },
        { hu: "Betanított munkás", en: "Unskilled Worker", de: "Angelernter Arbeiter" },
        { hu: "Rendszergazda", en: "System Administrator", de: "Systemadministrator" },
        { hu: "Lakatos", en: "Locksmith", de: "Schlosser" },
        { hu: "Villanyszerelő", en: "Electrician", de: "Elektriker" },
        { hu: "Kőműves", en: "Bricklayer", de: "Maurer" },
        { hu: "Hegesztő", en: "Welder", de: "Schweißer" },
        { hu: "Asztalos", en: "Carpenter", de: "Tischler" },
        { hu: "Burkoló", en: "Tiler", de: "Fliesenleger" },
        { hu: "Festő-mázoló", en: "Painter", de: "Maler" },
        { hu: "Vízvezetékszerelő", en: "Plumber", de: "Klempner" },
        { hu: "Autószerelő", en: "Auto Mechanic", de: "Kfz-Mechaniker" },
        { hu: "Karosszéria lakatos", en: "Body Repairer", de: "Karosseriebauer" },
        { hu: "Felszolgáló", en: "Waiter / Waitress", de: "Kellner" },
        { hu: "Pultos", en: "Bartender", de: "Barmann" },
        { hu: "Konyhai kisegítő", en: "Kitchen Assistant", de: "Küchenhilfe" },
        { hu: "Takarító", en: "Cleaner", de: "Reinigungskraft" },
        { hu: "Biztonsági őr", en: "Security Guard", de: "Sicherheitskraft" },
        { hu: "Futár", en: "Courier", de: "Kurier" },
        { hu: "Targoncavezető", en: "Forklift Driver", de: "Staplerfahrer" },
        { hu: "Logisztikai ügyintéző", en: "Logistics Assistant", de: "Logistikassistent" },
        { hu: "Raktárvezető", en: "Warehouse Manager", de: "Lagerleiter" },
        { hu: "Irodai adminisztrátor", en: "Office Clerk", de: "Bürokraft" },
        { hu: "Könyvelő", en: "Accountant", de: "Buchhalter" },
        { hu: "HR munkatárs", en: "HR Officer", de: "Personalmitarbeiter" },
        { hu: "Értékesítő", en: "Sales Representative", de: "Außendienstmitarbeiter" },
        { hu: "Ügyfélszolgálati munkatárs", en: "Customer Service", de: "Kundenservice" },
        { hu: "Minőségellenőr", en: "Quality Inspector", de: "Qualitätsprüfer" },
        { hu: "CNC gépkezelő", en: "CNC Operator", de: "CNC-Bediener" },
        { hu: "Gépkezelő", en: "Machine Operator", de: "Maschinenführer" },
        { hu: "Karbantartó", en: "Maintenance Worker", de: "Instandhalter" },
        { hu: "Kertész", en: "Gardener", de: "Gärtner" },
        { hu: "Ápoló", en: "Nurse", de: "Pflegekraft" },
        { hu: "Gyógyszertári asszisztens", en: "Pharmacy Assistant", de: "Apothekenhelfer" },
        { hu: "Szoftverfejlesztő", en: "Software Developer", de: "Softwareentwickler" },
        { hu: "Projektmenedzser", en: "Project Manager", de: "Projektleiter" },
        { hu: "Mérnök", en: "Engineer", de: "Ingenieur" }
    ],
    positions: [
        { hu: "Alkalmazott", en: "Employee", de: "Angestellter" },
        { hu: "Műszakvezető", en: "Shift Supervisor", de: "Schichtleiter" },
        { hu: "Csoportvezető", en: "Team Leader", de: "Teamleiter" },
        { hu: "Középvezető", en: "Middle Manager", de: "Abteilungsleiter" },
        { hu: "Gyakornok", en: "Intern", de: "Praktikant" },
        { hu: "Munkavezető", en: "Foreman", de: "Polier" },
        { hu: "Vezérigazgató", en: "CEO", de: "Geschäftsführer" },
        { hu: "Egyéni vállalkozó", en: "Freelancer", de: "Freiberufler" },
        { hu: "Betanított munkás", en: "Semi-skilled worker", de: "Angelernter" },
        { hu: "Külsős munkatárs", en: "Contractor", de: "Externer Mitarbeiter" },
        { hu: "Részlegvezető", en: "Department Head", de: "Bereichsleiter" },
        { hu: "Szakmai vezető", en: "Technical Lead", de: "Fachlicher Leiter" }
    ]
};
